class ComponentRotation(Enum,IComparable,IFormattable,IConvertible):
 """
 ComponentRotation property of DividedSurface.
 See Autodesk.Revit.DB.DividedSurface.
 
 enum ComponentRotation,values: Angle0 (0),Angle180 (180),Angle270 (270),Angle90 (90)
 """
 def __eq__(self,*args):
  """ x.__eq__(y) <==> x==yx.__eq__(y) <==> x==yx.__eq__(y) <==> x==y """
  pass
 def __format__(self,*args):
  """ __format__(formattable: IFormattable,format: str) -> str """
  pass
 def __ge__(self,*args):
  pass
 def __gt__(self,*args):
  pass
 def __init__(self,*args):
  """ x.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signature """
  pass
 def __le__(self,*args):
  pass
 def __lt__(self,*args):
  pass
 def __ne__(self,*args):
  pass
 def __reduce_ex__(self,*args):
  pass
 def __str__(self,*args):
  pass
 Angle0=None
 Angle180=None
 Angle270=None
 Angle90=None
 value__=None

